const KEYWORD_DEFINITIONS = [
  { id: "auditor", label: "Auditor", keyword: "auditor" },
  { id: "audit-and-auditor-related-works", label: "Audit and Auditor related works", keyword: "audit and auditor related works" },
  { id: "income-tax", label: "Income Tax", keyword: "income tax" },
  { id: "gst-registration", label: "GST Registration", keyword: "gst registration" },
  { id: "fssai", label: "Fssai", keyword: "fssai" },
  { id: "gst-filings", label: "GST filings", keyword: "gst filings" },
  { id: "food-licence", label: "Food Licence", keyword: "food licence" },
  { id: "labour-licence", label: "Labour licence", keyword: "labour licence" },
  { id: "shop-and-establishment", label: "Shop and establishment", keyword: "shop and establishment" },
  { id: "shop-registration", label: "Shop registration", keyword: "shop registration" },
  { id: "company-registration", label: "Company registration", keyword: "company registration" },
  { id: "msme", label: "Msme", keyword: "msme" },
  { id: "import-export-code", label: "Import export code", keyword: "import export code" },
  { id: "iec", label: "IEC", keyword: "iec" },
  { id: "private-limited-company", label: "Private limited company", keyword: "private limited company" },
  { id: "tax-consultant", label: "Tax Consultant", keyword: "tax consultant" },
  { id: "accounting", label: "Accounting", keyword: "accounting" },
  { id: "book-keeping", label: "Book keeping", keyword: "book keeping" },
  { id: "tally-accountant", label: "Tally accountant", keyword: "tally accountant" },
  { id: "startup-india-registration", label: "Startup India Registration", keyword: "startup india registration" },
  { id: "mca-filling", label: "MCA filling", keyword: "mca filling" },
  { id: "roc-filling", label: "Roc filling", keyword: "roc filling" },
  { id: "director-kyc", label: "Director kyc", keyword: "director kyc" },
  { id: "partnership-registration", label: "Partnership Registration", keyword: "partnership registration" },
  { id: "trust-registration", label: "Trust registration", keyword: "trust registration" },
  { id: "ngo-registration", label: "NGO Registration", keyword: "ngo registration" },
  { id: "society-registration", label: "Society Registration", keyword: "society registration" },
  { id: "co-operative-society-registration", label: "Co operative society registration", keyword: "co operative society registration" },
  { id: "80g-registration", label: "80G registration", keyword: "80g registration" },
  { id: "12a-registration", label: "12A registration", keyword: "12a registration" },
  { id: "association-registration", label: "Association registration", keyword: "association registration" },
  { id: "apartment-association-registration", label: "Apartment association registration", keyword: "apartment association registration" },
  { id: "association-audit", label: "Association audit", keyword: "association audit" },
  { id: "trust-audit", label: "Trust audit", keyword: "trust audit" },
  { id: "nidhi-company", label: "Nidhi company", keyword: "nidhi company" },
  { id: "finance-registration", label: "Finance registration", keyword: "finance registration" },
  { id: "pawn-broker-registration", label: "Pawn broker registration", keyword: "pawn broker registration" },
  { id: "halal-registration", label: "Halal registration", keyword: "halal registration" },
  { id: "trademark-registration", label: "Trademark registration", keyword: "trademark registration" },
  { id: "logo-registration", label: "Logo registration", keyword: "logo registration" },
  { id: "iso-registration", label: "Iso registration", keyword: "iso registration" },
  { id: "chit-fund-registration", label: "Chit fund registration", keyword: "chit fund registration" },
  { id: "15ca-cb", label: "15CA CB", keyword: "15ca cb" },
  { id: "net-worth-certificate", label: "Net worth certificate", keyword: "net worth certificate" },
  { id: "turnover-certificate", label: "Turnover certificate", keyword: "turnover certificate" },
  { id: "udin", label: "UDIN", keyword: "udin" },
  { id: "gst-notices-handling", label: "GST Notices Handling", keyword: "gst notices handling" },
  { id: "income-tax-notice-handling", label: "Income tax notice handling", keyword: "income tax notice handling" },
  { id: "tds-filling", label: "TDS filling", keyword: "tds filling" },
  { id: "professional-tax", label: "Professional Tax", keyword: "professional tax" },
  { id: "tax-audit", label: "Tax audit", keyword: "tax audit" },
  { id: "esi-and-pf", label: "ESI and PF", keyword: "esi and pf" },
  { id: "gem-registration", label: "GEM registration", keyword: "gem registration" },
  { id: "llp-registration", label: "LLP registration", keyword: "llp registration" },
  { id: "limited-company-registration", label: "Limited company registration", keyword: "limited company registration" },
  { id: "lut-registration", label: "LUT registration", keyword: "lut registration" },
  { id: "apeda-registration", label: "APEDA registration", keyword: "apeda registration" },
  { id: "tax-advisor", label: "Tax Advisor", keyword: "tax advisor" },
  { id: "income-tax-return-preparation", label: "Income tax return preparation", keyword: "income tax return preparation" },
  { id: "new-business-tax-consulting", label: "New business tax consulting", keyword: "new business tax consulting" },
  { id: "tax-authority-audit-representation", label: "Tax authority audit representation", keyword: "tax authority audit representation" },
  { id: "tax-planning", label: "Tax planning", keyword: "tax planning" },
  { id: "tax-problem-consulting", label: "Tax problem consulting", keyword: "tax problem consulting" },
];

export const TERMS = KEYWORD_DEFINITIONS.map((term) => ({
  ...term,
  region: "Karnataka",
  geo: "IN-KA"
}));

export function configuredBaseline(term) {
  if (!term?.baselineEnv) return null;
  const value = Number(process.env[term.baselineEnv] || "");
  return Number.isFinite(value) && value > 0 ? value : null;
}
